version: '3.8'

networks:
  my_macvlan_network:
    driver: macvlan
    driver_opts:
      parent: ens33 # Reemplaza esto con el nombre de la interfaz del host que deseas utilizar
    ipam:
      config:
        - subnet: <tu_subnet_elegido>  # Reemplaza esto con tu subnet deseado, p. ej., "192.168.1.0/24"
        - gateway: <tu_gateway_elegido>  # Reemplaza esto con tu gateway deseado, p. ej., "

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - my_macvlan_network

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - my_macvlan_network
